## Define your key variable
variable "ansible-terraform_name" {
  type        = string
  default     = local.environment-user
  description = "Key-pair generated by Terraform"
}

variable "instance_type" {
  type = string
  default = "t3.micro"
}